package com.dbdeployer.pipeline.model;

public enum DeployErrorCode {
    IMAGE_NOT_FOUND,
    IMAGE_PULL_TIMEOUT,
    IMAGE_PULL_FAILED,
    PORT_ALREADY_IN_USE,
    VOLUME_CREATE_FAILED,
    CONTAINER_NAME_CONFLICT,
    CONTAINER_CREATE_FAILED,
    CONTAINER_START_FAILED,
    CONTAINER_EXITED_IMMEDIATELY,
    DOCKER_NOT_AVAILABLE,
    UNEXPECTED_ERROR
}
